# This file contains the information needed for Shopify to authenticate
# requests and edit/update your remote theme files.
#
# 1. Set up a private app (https://help.shopify.com/api/guides/api-credentials#generate-private-app-credentials)
#    with "Read and write" permissions for "Theme templates and theme assets".
# 2. Replace the required variables for each environment below.
#
# password, theme_id, and store variables are required.
#
# For more information on this config file:
#   Configuration variables | http://shopify.github.io/themekit/configuration/
#   Ignore patterns | http://shopify.github.io/themekit/ignores/

---

development:
  password: 1248d351917acf42c3009ba2cfeabc0d
  theme_id: 44074467439
  store: loandsons-dev.myshopify.com
  ignore_files:
    - settings_data.json # leave this line to avoid resetting theme settings

production:
  password: 1248d351917acf42c3009ba2cfeabc0d
  theme_id: 44074467439
  store: loandsons-dev.myshopify.com
  ignore_files:
    - settings_data.json # leave this line to avoid resetting theme settings